modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"
issueTrackerURL="https://github.com/tbhmens/TheSource"
[[mods]]
modId = "thesource"
version = "${version}"
displayName = "The Source"
authors = "tbhmens"
description = ''''''

[[dependencies.thesource]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thesource]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"